import type { MarketplaceVenue, EventType, Testimonial } from '~/types'

export default defineEventHandler(() => {
  const venues: MarketplaceVenue[] = [
    {
      id: 1,
      name: 'Grand Ballroom',
      hotel: 'Marriott Downtown',
      location: 'New York, NY',
      capacity: 200,
      pricePerDay: 4500,
      rating: 4.8,
      reviewCount: 89,
      image: 'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?w=600&h=400&fit=crop',
      amenities: ['AV Equipment', 'Catering', 'Wi-Fi', 'Stage'],
      eventType: 'conferences',
    },
    {
      id: 2,
      name: 'The Boardroom',
      hotel: 'Hilton Midtown',
      location: 'New York, NY',
      capacity: 16,
      pricePerDay: 1200,
      rating: 4.6,
      reviewCount: 54,
      image: 'https://images.unsplash.com/photo-1577412647305-991150c7d163?w=600&h=400&fit=crop',
      amenities: ['4K Display', 'Video Conferencing', 'Wi-Fi', 'Catering'],
      eventType: 'workshops',
    },
    {
      id: 3,
      name: 'Skyline Terrace',
      hotel: 'Ritz-Carlton',
      location: 'San Francisco, CA',
      capacity: 80,
      pricePerDay: 3200,
      rating: 4.9,
      reviewCount: 112,
      image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=600&h=400&fit=crop',
      amenities: ['Outdoor Space', 'Catering', 'Wi-Fi', 'Built-in Bar'],
      eventType: 'product-launches',
    },
    {
      id: 4,
      name: 'Innovation Lab',
      hotel: 'Hyatt Regency',
      location: 'Chicago, IL',
      capacity: 40,
      pricePerDay: 1800,
      rating: 4.7,
      reviewCount: 73,
      image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=600&h=400&fit=crop',
      amenities: ['Whiteboards', 'Wi-Fi', 'Catering', 'Breakout Rooms'],
      eventType: 'corporate-workshops',
    },
    {
      id: 5,
      name: 'Crystal Hall',
      hotel: 'Four Seasons',
      location: 'Miami, FL',
      capacity: 300,
      pricePerDay: 5800,
      rating: 4.9,
      reviewCount: 145,
      image: 'https://images.unsplash.com/photo-1564540574859-0dfb5af6f2c6?w=600&h=400&fit=crop',
      amenities: ['Full AV Suite', 'Catering', 'Wi-Fi', 'Stage', 'Green Room'],
      eventType: 'seminars',
    },
    {
      id: 6,
      name: 'Lakeside Retreat Room',
      hotel: 'Sheraton Lakeside',
      location: 'Austin, TX',
      capacity: 30,
      pricePerDay: 1500,
      rating: 4.5,
      reviewCount: 38,
      image: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=600&h=400&fit=crop',
      amenities: ['Wi-Fi', 'Catering', 'Outdoor Deck', 'Fireplace'],
      eventType: 'team-retreats',
    },
  ]

  const eventTypes: EventType[] = [
    { id: 'conferences', name: 'Conferences', icon: 'mdi-presentation', description: 'Multi-day conferences with full AV support' },
    { id: 'corporate-workshops', name: 'Corporate Workshops', icon: 'mdi-school', description: 'Hands-on training and team building' },
    { id: 'seminars', name: 'Seminars', icon: 'mdi-microphone', description: 'Expert-led talks and panel discussions' },
    { id: 'team-retreats', name: 'Team Retreats', icon: 'mdi-tent', description: 'Off-site strategy and bonding sessions' },
    { id: 'product-launches', name: 'Product Launches', icon: 'mdi-rocket-launch', description: 'Showcase new products in style' },
    { id: 'networking', name: 'Networking Events', icon: 'mdi-handshake', description: 'Mixers, happy hours, and socials' },
  ]

  const testimonials: Testimonial[] = [
    {
      id: 1,
      name: 'Sarah Mitchell',
      avatar: 'https://i.pravatar.cc/80?img=32',
      title: 'Event Director',
      company: 'TechCorp',
      quote: 'We booked the Grand Ballroom for our annual summit and it exceeded every expectation. The space was stunning, the AV flawless, and the catering was exceptional.',
      rating: 5,
    },
    {
      id: 2,
      name: 'James Rivera',
      avatar: 'https://i.pravatar.cc/80?img=53',
      title: 'VP of Learning & Development',
      company: 'Meridian Health',
      quote: 'The Innovation Lab at Hyatt Regency has been our go-to for quarterly workshops. The breakout rooms and whiteboard walls make it perfect for collaborative sessions.',
      rating: 5,
    },
    {
      id: 3,
      name: 'Priya Nair',
      avatar: 'https://i.pravatar.cc/80?img=45',
      title: 'General Manager',
      company: 'Marriott Downtown',
      quote: 'Listing our spaces on this platform has been a game-changer. We\'re seeing 30% higher occupancy for our meeting rooms and attracting corporate clients we never reached before.',
      rating: 4,
    },
    {
      id: 4,
      name: 'Michael Torres',
      avatar: 'https://i.pravatar.cc/80?img=68',
      title: 'Head of Events',
      company: 'StartupLab',
      quote: 'The Skyline Terrace was the perfect venue for our product unveiling. Booking took 3 minutes — no back-and-forth, no hidden fees. Exactly what event planning should be.',
      rating: 5,
    },
  ]

  return { venues, eventTypes, testimonials }
})
