import type { MarketplaceWorkshop, Category, Testimonial } from '~/types'

export default defineEventHandler(() => {
  const workshops: MarketplaceWorkshop[] = [
    {
      id: 1,
      title: 'Hand-Building Pottery Basics',
      host: 'Emma Chen',
      hostAvatar: '',
      category: 'pottery',
      price: 45,
      rating: 4.8,
      reviewCount: 124,
      spotsLeft: 3,
      totalSpots: 12,
      image: 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=600&h=400&fit=crop',
      date: '2026-07-12',
      time: '10:00 AM',
    },
    {
      id: 2,
      title: 'Sourdough Baking Workshop',
      host: 'Marco Rossi',
      hostAvatar: '',
      category: 'cooking',
      price: 35,
      rating: 4.9,
      reviewCount: 89,
      spotsLeft: 1,
      totalSpots: 10,
      image: 'https://images.unsplash.com/photo-1549931319-a54575346735?w=600&h=400&fit=crop',
      date: '2026-07-13',
      time: '2:00 PM',
    },
    {
      id: 3,
      title: 'Sunrise Yoga by the River',
      host: 'Priya Patel',
      hostAvatar: '',
      category: 'yoga',
      price: 25,
      rating: 4.7,
      reviewCount: 203,
      spotsLeft: 8,
      totalSpots: 15,
      image: 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=600&h=400&fit=crop',
      date: '2026-07-14',
      time: '6:30 AM',
    },
    {
      id: 4,
      title: 'Portrait Photography Masterclass',
      host: 'David Kim',
      hostAvatar: '',
      category: 'photography',
      price: 65,
      rating: 4.6,
      reviewCount: 67,
      spotsLeft: 2,
      totalSpots: 8,
      image: 'https://images.unsplash.com/photo-1452587925148-ce544e77e70d?w=600&h=400&fit=crop',
      date: '2026-07-15',
      time: '11:00 AM',
    },
    {
      id: 5,
      title: 'Acrylic Painting for Beginners',
      host: 'Sophie Laurent',
      hostAvatar: '',
      category: 'painting',
      price: 55,
      rating: 4.8,
      reviewCount: 156,
      spotsLeft: 5,
      totalSpots: 14,
      image: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=600&h=400&fit=crop',
      date: '2026-07-16',
      time: '1:00 PM',
    },
    {
      id: 6,
      title: 'Guitar for Absolute Beginners',
      host: 'James Taylor',
      hostAvatar: '',
      category: 'music',
      price: 40,
      rating: 4.5,
      reviewCount: 98,
      spotsLeft: 4,
      totalSpots: 6,
      image: 'https://images.unsplash.com/photo-1510915361894-db8b60106cb1?w=600&h=400&fit=crop',
      date: '2026-07-17',
      time: '4:00 PM',
    },
  ]

  const categories: Category[] = [
    { id: 'cooking', name: 'Cooking', icon: 'mdi-chef-hat', color: '#E07A5F' },
    { id: 'pottery', name: 'Pottery', icon: 'mdi-pot-steam', color: '#F59E0B' },
    { id: 'painting', name: 'Painting', icon: 'mdi-palette', color: '#81B29A' },
    { id: 'yoga', name: 'Yoga', icon: 'mdi-meditation', color: '#14B8A6' },
    { id: 'photography', name: 'Photography', icon: 'mdi-camera', color: '#E07A5F' },
    { id: 'music', name: 'Music', icon: 'mdi-guitar-acoustic', color: '#D97706' },
    { id: 'fitness', name: 'Fitness', icon: 'mdi-dumbbell', color: '#81B29A' },
    { id: 'dance', name: 'Dance', icon: 'mdi-human-handsup', color: '#F59E0B' },
  ]

  const testimonials: Testimonial[] = [
    {
      id: 1,
      name: 'Alisha R.',
      avatar: 'https://i.pravatar.cc/80?img=1',
      title: 'Pottery Enthusiast',
      company: '',
      quote: 'I booked a wheel-throwing workshop on a whim and it was the best decision I\'ve made this year. The instructor was patient and the studio had such a welcoming vibe.',
      rating: 5,
    },
    {
      id: 2,
      name: 'Marcus T.',
      avatar: 'https://i.pravatar.cc/80?img=3',
      title: 'Home Baker',
      company: '',
      quote: 'The sourdough workshop was incredible. I went from killing my starter to baking bakery-quality bread in one session. Already signed up for the advanced class!',
      rating: 5,
    },
    {
      id: 3,
      name: 'Leila K.',
      avatar: 'https://i.pravatar.cc/80?img=5',
      title: 'Yoga Practitioner',
      company: '',
      quote: 'The riverside yoga session was magical. Booking was seamless — I picked my spot, paid, and got a reminder the day before. Couldn\'t be easier.',
      rating: 4,
    },
    {
      id: 4,
      name: 'Owen S.',
      avatar: 'https://i.pravatar.cc/80?img=7',
      title: 'Aspiring Photographer',
      company: '',
      quote: 'David\'s portrait photography workshop taught me more in 3 hours than I learned in a year of YouTube tutorials. Worth every penny.',
      rating: 5,
    },
  ]

  return { workshops, categories, testimonials }
})
